# Generated by Django 4.2.6 on 2024-05-16 19:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_gaulke_contabil_v2', '0003_alter_model_tb_clients_cod_sistema_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model_tb_clients',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 16, 16, 30, 34, 91312)),
        ),
        migrations.AlterField(
            model_name='model_tb_clients',
            name='update_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 16, 16, 30, 34, 91312)),
        ),
        migrations.AlterField(
            model_name='model_tb_imposto_de_renda',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 16, 16, 30, 34, 91312)),
        ),
        migrations.AlterField(
            model_name='model_tb_imposto_de_renda',
            name='update_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 16, 16, 30, 34, 91312)),
        ),
        migrations.AlterField(
            model_name='model_tb_imposto_de_renda',
            name='valor_ano_anterior',
            field=models.CharField(default='', max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='model_tb_imposto_de_renda',
            name='valor_ano_atual',
            field=models.CharField(default='', max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='model_tb_imposto_de_renda_comments',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 16, 16, 30, 34, 106936)),
        ),
        migrations.AlterField(
            model_name='model_tb_imposto_de_renda_comments',
            name='update_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 16, 16, 30, 34, 106936)),
        ),
    ]
